# Generated by Django 2.0.5 on 2018-08-23 01:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import news.upload_path


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('slug', models.CharField(max_length=10, unique=True)),
                ('news', models.TextField()),
                ('image', models.ImageField(upload_to=news.upload_path.post_image)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
