# Generated by Django 2.0.5 on 2018-08-11 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20180811_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
